
'''
This file contains a dictionary with the full name and shorthand for
all the countries and subcountry regions in the dataset.
'''

statemap =  {
    'tx':'Texas',
    'gb':'Great Britain',
    'hi':'Hawaii',
    'tn':'Tennessee',
    'ct':'Connecticut',
    'al':'Alabama',
    'fl':'Florida',
    'ca':'California',
    'nc':'North Carolina',
    'ny':'New York',
    'ky':'Kentucky',
    'mi':'Michigan',
    'ma':'Massachusetts',
    'ks':'Kansas',
    'sc':'South Carolina',
    'wa':'Washington',
    'ab':'Alberta',
    'co':'Colorado',
    'nh':'New Hampshire',
    'wi':'Wisconsin',
    'me':'Maine',
    'ga':'Georgia',
    'pa':'Pennsylvania',
    'il':'Illinois',
    'ar':'Arkansas',
    'on':'Ontario',
    'mo':'Missouri',
    'oh':'Ohio',
    'in':'Indiana',
    'az':'Arizona',
    'mn':'Minnesota',
    'nv':'Nevada',
    'nf':'Newfoundland and Labrador',
    'ne':'Nebraska',
    'or':'Oregon',
    'bc':'British Columbia',
    'ia':'Great Britain',
    'ia':'Iowa',
    'au':'Australia',
    'va':'Virginia',
    'id':'Idaho',
    'nm':'New Mexico',
    'nj':'New Jersey',
    'mb':'Manitoba',
    'wv':'West Virginia',
    'ok':'Oklahoma',
    'ri':'Rhode Island',
    'nb':'New Brunswick',
    'vt':'Vermont',
    'la':'Louisiana',
    'pr':'Puerto Rico',
    'ak':'Alaska',
    'ms':'Mississippi',
    'ut':'Utah',
    'md':'Maryland',
    'mt':'Montana',
    'sk':'Saskatchewan',
    'wy':'Wyoming',
    'pq':'Quebec',
    'de':'Germany',
    'ns':'Nova Scotia',
    'qc':'Quebec',
    'nd':'North Dakota',
    'dc':'Washington DC',
    'nt':'Northern Territory Australia',
    'sa':'Saskatchewan',
    'yt':'Yukon Territory',
    'yk':'Yukon Territory',
    'pe':'Prince Edward Island'
}